#include "../include/_alib.hpp"
#include "../include/_ast.hpp"

__def_ast_tid__(CompUnitAST, COMP_UNIT_AST);
__def_ast_tid__(FuncDefAST, FUNC_DEF_AST);
__def_ast_tid__(FuncTypeAST, FUNC_TYPE_AST);
__def_ast_tid__(BlockAST, BLOCK_AST);
__def_ast_tid__(StmtAST, STMT_AST);
__def_ast_tid__(ExprAST, EXPR_AST);
__def_ast_tid__(PrimaryExprAST, PRIMARY_EXPR_AST);
__def_ast_tid__(NumberAST, NUMBER_AST);
__def_ast_tid__(UnaryExpAST, UNARY_EXPR_AST);
__def_ast_tid__(UnaryOpAST, UNARY_OP_AST);
__def_ast_tid__(MulExpAST, MUL_EXPR_AST);
__def_ast_tid__(AddExpAST, ADD_EXPR_AST);
__def_ast_tid__(BinOpAST, BINARY_OP_AST);
__def_ast_tid__(RelExpAST, REL_EXPR_AST);
__def_ast_tid__(EqExpAST, EQ_EXPR_AST);
__def_ast_tid__(CmpOpAST, CMP_OP_AST);
__def_ast_tid__(LAndExpAST, LAND_EXPR_AST);
__def_ast_tid__(LOrExpAST, LOR_EXPR_AST);
__def_ast_tid__(BlockItemAST, BLOCK_ITEM_AST);
__def_ast_tid__(LValAST, LVAL_AST);
__def_ast_tid__(DeclAST, DECL_AST);
__def_ast_tid__(ConstDeclAST, CONST_DECL_AST);
__def_ast_tid__(BTypeAST, BTYPE_AST);
__def_ast_tid__(ConstDefAST, CONST_DEF_AST);
__def_ast_tid__(ConstInitValAST, CONST_INIT_VAL_AST);
__def_ast_tid__(ConstExpAST, CONST_EXPR_AST);

